services:
  - type: web
    name: iot-cargo-wear
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py & streamlit run app.py --server.port $PORT --server.address 0.0.0.0
